config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit]
  resources :users, only: [:index, :show, :edit, :update]

  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  patch 'books/:id' => 'books#update' , as: 'update_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

has_one_attached :profile_image

 validates :name, presence: true,
                  uniqueness: true,
                  length: { minimum: 2 , maximum: 20 }
 validates :introduction, presence: false,
                          length: { maximum: 50 }

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:create] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @users = User.all
    @books = Book.all
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:update] = "You have updated book successfully."
      redirect_to book_path
    else
      @books = Book.all
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  add_flash_types :success, :info, :warning, :danger


  def index
    @users = User.all
    @books = Book.all
  end

  def show
    @users = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
  end

  def edit
    @users = User.find(params[:id])
    @books = Book.all
  end

  def update
    @users = User.find(params[:id])
    @users.update(user_params)
    if @users.save
      flash[:update] ="You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  private
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_session_path
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% books.first(1).each do |book| %>
 <h2>User Info</h2>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <table class="table">
      <thead>
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= book.user.name %></th>
        </tr>
        <tr>
          <th >introdaction</th>
          <th><%= book.user.introduction %></th>
        </tr>
      </thead>
      </table>
      <div class="row">
        <%= link_to(edit_user_path(@users), class:"btn btn-outline-secondary btn-sm  btn-block") do %>
          <i class="fa-solid fa-user-gear"></i>
        <% end %>
      </div>
<% end %>

app/views/books/_list2.html.erb
<h2>New book</h2>
<%= form_with model: Book.new do |f| %>
  <div class="form-group">
    <label for="title">Title</label><br>
    <%= f.text_field :title, class:"form-control title" %>
  </div>
  <div class="form-group">
    <label for="body">Opinion</label><br>
    <%= f.text_area :body, class:"form-control body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
 <% end %>

app/views/books/_list3.html.erb
  <h2>User Info</h2>
        <%= image_tag user.get_profile_image(63,63) %>
        <table class="table">
        <thead>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th >introdaction</th>
            <th><%= user.introduction %></th>
          </tr>
        </thead>
        </table>
        <div class="row">
          <%= link_to(edit_user_path(user), class:"btn btn-outline-secondary btn-sm  btn-block") do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

app/views/books/_list4.html.erb
<% books.first(1).each do |book| %>
  <h2>User Info</h2>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <table class="table">
        <thead>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= book.user.name %></th>
          </tr>
          <tr>
            <th >introdaction</th>
            <th><%= book.user.introduction %></th>
          </tr>
        </thead>
        </table>
        <div class="row">
          <%= link_to(edit_user_path(@users), class:"btn btn-outline-secondary btn-sm  btn-block") do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <div id="error_message">
          <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          <% end %>
        </div>
        <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class:"form-control book_body" %>
            </div>
            <div class="form-group">
              <%= f.submit 'Update Book', class:"btn btn-success" %>
            </div>
        <% end %>
        <%= link_to "Show", book_path %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_message">
    <% if @book.errors.any? %>
    <h3 class="text-danger"><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= render 'list3' , books: @books, user: current_user %><br>
      <%= render 'list2' , books: @books, user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(40,40)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, "/books/#{book.id}"  %></td>
              <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model: Book.new do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label><br>
    <%= f.text_field :book_title, class:"form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_body">Opinion</label><br>
    <%= f.text_area :book_body, class:"form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
 <% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container">
 <div class="row">
  <div class="col-md-3">
    <%= render 'list3', books: @books, user: @book.user %><br>
    <%= render 'list2' , books: @books, user: @book.user %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
   <table class="table">
    <tbody>
     <tr>
      <td><%= image_tag @book.user.get_profile_image(40,40) %><br><%= link_to @book.user.name, user_path(@book.user.id) %></td>
      <td><%= link_to @book.title, "/books/#{@book.id}"  %></td>
      <td><%= @book.body %></td>
      <% if @book.user == current_user %>
      <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-success'  %></td>
      <td><%= link_to "Destroy", book_path(@book), class: 'btn btn-danger', method: :delete %></td>
      <% end %>
     </tr>
    </tbody>
   </table>
  </div>
 </div>

</div>

app/views/homes/about.html.erb
<p></p>
<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
</div>

app/views/homes/top.html.erb
<p></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>

    <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>

    <p>you can share and exchange your opinions , inpressions , and emotions</p>

    <p>about various books!</p>

    <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in" >Log in</a>
        </div>

        <div class="row">
          <a class="btn btn-success btn-sm btn-block mb-3 sign_up" href="/users/sign_up" >Sign up</a>
        </div>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
      　  　<% if user_signed_in? %>
        　 <li><%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
           <i class="fas fa-home"></i> Home<% end %></li>
           <li><%= link_to users_path, class: 'nav-link text-light' do %>
           <i class="fas fa-users"></i> Users<% end %></li>
           <li><%= link_to books_path, class: 'nav-link text-light' do %>
           <i class="fas fa-book-open"></i> Books<% end %></li>
           <li><%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
           <i class="fas fa-sign-out-alt"></i> Log out<% end %></li>
           <% else %>
           <li><%= link_to root_path, class: 'nav-link text-light' do %>
           <i class="fas fa-home"></i> Home<% end %></li>
           <li><%= link_to about_path, class: 'nav-link text-light' do %>
           <i class="fas fa-link"></i> About<% end %></li>
           <li><%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
           <i class="fas fa-user-plus"></i> Sign up<% end %></li>
           <li><%= link_to new_user_session_path, class: 'nav-link text-light' do %>
           <i class="fas fa-sign-in-alt"></i> Log in<% end %></li>
           <% end %>
           </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <%= msg.html_safe %>
      </div>
    <% end %>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p></p>
<div class="container">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div id="error_message">
        <% if @users.errors.any? %>
        <h2><%= @users.errors.count %>errors prohibited this book from being saved:</h2>
        <ul>
          <% @users.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      </div>
        <%= form_with model: @users, local: true do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, class:"form-control user_name" %>
          </div>
          <div class="form-group">
            <label for="inputImage">Image</label><br>
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, class:"form-control user_introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update User', class:"btn btn-secondary" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list3', books: @books, user: current_user %><br>
      <%= render 'books/list2', books: @books, user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(40,40) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list3', books: @books, user: @users %><br>
      <%=render 'books/list2', books: @books, user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
         <% @books.each do |book| %>
         <tr>
           <td><%= link_to image_tag(book.user.get_profile_image(40,40)), user_path(book.user.id) %></td>
           <td><%= link_to book.title, book_path(book.id)  %></td>
           <td><%= book.body %></td>
         </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>